- name: Creating files dirs
  file: path={{ item }} state=directory mode=755
  with_items:
    - "{{ bashfiles_dir }}"
    - "{{ includefiles_dir }}"

- name: Copy bashfiles
  copy: src=bashfiles/ dest={{ bashfiles_dir  }} mode=744

- name: Copy include files
  copy: src=includefiles/ dest={{ includefiles_dir  }} mode=744

- name: Copy git files
  shell: cd {{ bashfiles_dir }} && wget -nc {{ item }}
  with_items:
    - "https://raw.githubusercontent.com/git/git/master/contrib/completion/git-prompt.sh"
    - "https://raw.githubusercontent.com/git/git/master/contrib/completion/git-completion.bash"

- name: .bash_profile file get file info
  stat: path=~/.bash_profile
  register: bash_profile_stat

- name: Check bash_profile file
  shell: cat ~/.bash_profile | grep {{ file_gen_flag }}
  register: is_custom_bash_profile
  when: bash_profile_stat.stat.exists
  ignore_errors: True

- name: Backup bash_profile if custom file exists
  command: mv ~/.bash_profile ~/.bash_profile_backup
  when: is_custom_bash_profile.changed and is_custom_bash_profile.stdout == ""

- name: Copy bash_profile 
  template: src=bash_profile.tpl dest=~/.bash_profile
