- name: Copy bashfiles
  copy: src=./ dest={{ dotfiles_dir  }} mode=744
  tags:
    - dotfiles

- name: Copy bashrc
  template: src=bashfile.tpl dest={{ bashfile_path }} mode=744
  tags:
    - dotfiles

- name: Copy profile
  template: src=profile.tpl dest=~/.profile mode=744
  tags:
    - dotfiles