- name: Update and upgrade Homebrew
  homebrew: update_homebrew=yes upgrade_all=yes
  tags:
    - common
    - brew
    - upgrade
    - package-install

- name: Homebrew install packages
  homebrew: name={{ item }} state=latest
  with_items:
    - curl
    - wget
    - python
    - python3
    - vim
  tags:
    - common
    - brew
    - package-install
